### POST A PRODUCT
POST http://localhost:5000/products HTTP/1.1
Content-Type: application/json

{
    "name": "Geladeira",
    "price": 350,
    "description": "Uma ótima mesa de jantar!"
}

### GET ALL PRODUCTS
GET http://localhost:5000/products HTTP/1.1

### GET A SINGLE PRODUCT
GET  http://localhost:5000/products/64a574f642b63b777de1a6df HTTP/1.1

### UPDATE A PRODUCT
PATCH http://localhost:5000/products/update/64a5975e4a402891ef72fcf1 HTTP/1.1
Content-Type: application/json

{
    "name": "Computador",
    "price": 3500,
    "description": "Um ótimo computador para trabalhar e estudar!"
}

### DELELETE A PRODUCT
DELETE http://localhost:5000/products/delete/64a5975e4a402891ef72fcf1 HTTP/1.1